# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_MSTAR_MSC313_BDMA) += mstar-msc313-bdma.o
obj-$(CONFIG_MSTAR_MSC313_CMDQ) += mstar-msc313-cmdq.o
obj-$(CONFIG_MSTAR_MSC313_URDMA) += mstar-msc313-urdma.o
obj-$(CONFIG_SSTAR_SSD20XD_MOVEDMA) += sstar-ssd20xd-movedma.o
