/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef INCLUDE_SOC_MSTAR_PMSLEEP_H_
#define INCLUDE_SOC_MSTAR_PMSLEEP_H_

#define MSTAR_PMSLEEP_INTSTATUS				0x10
#define MSTAR_PMSLEEP_WAKEUPSOURCE			0x20
#define MSTAR_PMSLEEP_WAKEUPSOURCE_RTC			BIT(4)
#define MSTAR_PMSLEEP_REG24				0x24
#define MSTAR_PMSLEEP_REG24_POWEROFF			BIT(15)
#define MSTAR_PMSLEEP_WAKEINT_STATUS			0x38
#define MSTAR_PMSLEEP_PMLOCK				0x48
#define MSTAR_PMSLEEP_PMLOCK_UNLOCK			0xbabe
#define MSTAR_PMSLEEP_REG70				0x70
#define MSTAR_PMSLEEP_REG70_ISOEN2GPIO4			BIT(3)
#define MSTAR_PMSLEEP_REG70_LINKWKINT2GPIO4		BIT(2)
#define MSTARV7_PMSLEEP_RSTCNTRL			0xa4
#define MSTARV7_PMSLEEP_RSTCNTRL_CPUX_SW_RSTZ_8051	12
#define MSTAR_PMSLEEP_PMLED				0xa0
#define MSTARV7_PMSLEEP_SPI_UART_GPIO			0xd4
#define MSTAR_PMSLEEP_REGC8				0xc8
#define MSTAR_PMSLEEP_REGC8_MAGIC			0x9f8e
#define MSTAR_PMSLEEP_REGCC				0xcc
#define MSTAR_PMSLEEP_REGCC_MAGIC			0x9f8e
#define MSTARV7_PM_RESUMEADDR				0xec

#endif
