# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mstar specific clk
#

obj-$(CONFIG_MSTAR_MSC313_MPLL) += clk-msc313-mpll.o
obj-$(CONFIG_MSTAR_MSC313_CPUPLL) += clk-msc313-cpupll.o
obj-$(CONFIG_MSTAR_MSC313_UPLL) += clk-msc313-upll.o
obj-$(CONFIG_MSTAR_MSC313_LPLL) += clk-msc313-lpll.o
obj-$(CONFIG_MSTAR_MSC313_MIUPLL) += clk-msc313-miupll.o
obj-$(CONFIG_MSTAR_MSC313_SC_GP_CTRL_MUXES) += clk-msc313-sc-gp-ctrl-muxes.o
obj-$(CONFIG_MSTAR_MSC313_PM_MUXES) += clk-msc313-pm-muxes.o
obj-$(CONFIG_MSTAR_MSC313_CLKGEN) += clk-msc313-clkgen.o

obj-y += clk-mstar-pll_common.o \
	 clk-msc313-mux.o
