/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * Output definitions for the MStar/SigmaStar SC GP
 *
 * Copyright (C) 2021 Daniel Palmer <daniel@thingy.jp>
 */

#ifndef _DT_BINDINGS_CLOCK_MSTAR_MSC313_SC_GP_H
#define _DT_BINDINGS_CLOCK_MSTAR_MSC313_SC_GP_H

#define MSC313_SC_GP_EMAC_RX_MUX	0
#define MSC313_SC_GP_EMAC_RX		1
#define MSC313_SC_GP_EMAC_RX_REF_MUX	2
#define MSC313_SC_GP_EMAC_RX_REF	3
#define MSC313_SC_GP_EMAC_TX_MUX	4
#define MSC313_SC_GP_EMAC_TX		5
#define MSC313_SC_GP_EMAC_TX_REF_MUX	6
#define MSC313_SC_GP_EMAC_TX_REF	7

#define SSD20XD_SC_GP_EMAC_RX_MUX	0
#define SSD20XD_SC_GP_EMAC_RX		1
#define SSD20XD_SC_GP_EMAC_RX_REF_MUX	2
#define SSD20XD_SC_GP_EMAC_RX_REF	3
#define SSD20XD_SC_GP_EMAC_TX_MUX	4
#define SSD20XD_SC_GP_EMAC_TX		5
#define SSD20XD_SC_GP_EMAC_TX_REF_MUX	6
#define SSD20XD_SC_GP_EMAC_TX_REF	7

#define SSD20XD_SC_GP_EMAC1_RX_MUX	8
#define SSD20XD_SC_GP_EMAC1_RX		9
#define SSD20XD_SC_GP_EMAC1_RX_REF_MUX	10
#define SSD20XD_SC_GP_EMAC1_RX_REF	11
#define SSD20XD_SC_GP_EMAC1_TX_MUX	12
#define SSD20XD_SC_GP_EMAC1_TX		13
#define SSD20XD_SC_GP_EMAC1_TX_REF_MUX	14
#define SSD20XD_SC_GP_EMAC1_TX_REF	15

#define SSD20XD_SC_GP_SDIO_GATE_MUX	16
#define SSD20XD_SC_GP_SDIO_GATE		17

#endif
